<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>632302ba-6a8f-4eba-82bc-86f57a30cd71</testSuiteGuid>
   <testCaseLink>
      <guid>f0d41377-04a4-4f92-8fc4-a27243e721e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Weryfikacja doładowania telefonu/Logowanie do aplikacji/Logowanie do aplikacji z poprawnymi danymi</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df9b9f53-5582-4528-be84-07291bf000a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4bd9f563-1dfb-44a3-b1bb-83e1451a6620</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Weryfikacja doładowania telefonu/Wykonanie przelewu/Wykonanie przelewu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0916c811-8e5b-4f38-a285-be66b3c7e508</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee5a658d-82e7-4f39-b7d4-b16ffa95ad19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>707d78ec-7559-4d52-94c7-3092b535889c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b7b6019a-5545-4a61-a4da-1d07af6a7fb0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Weryfikacja doładowania telefonu/Doładowanie telefonu/Sprawdzenie doladowania telefonu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edb7ddda-590e-44b0-8c5b-d6c190f2297b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
